-- Noor AlDhikr V82.0
-- هذا الملف توثيق فقط: تم تطبيق Migration V82.0 فعليًا على مشروع Supabase من داخل ChatGPT.
-- لا تحتاج لإعادة تشغيله لإصلاح صفحة المالك.
--
-- الحالة المؤكدة بعد التطبيق:
-- 1) ai_knowledge موجود وRLS مفعّل.
-- 2) حساب المالك موجود ونشط ومؤكد البريد.
-- 3) is_owner() و owner_portal_diagnostics() موجودتان.
-- 4) تم تضييق grants للـ anon/authenticated.
-- 5) تمت إضافة فهارس للأعمدة المرجعية المهمة.
--
-- سبب عطل الاتصال الأساسي الذي تم اكتشافه:
-- الرابط القديم كان يحتوي project ref خاطئ:
-- yankugxforcedvnatknhs
-- والصحيح:
-- yankugxfocedvnatknhs
select 'V82.0 migration already applied' as status;
